repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:

  - name: prometheus
    namespace: prometheus
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    values:
      - prometheus/values.yaml

  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    values:
      - ingress-nginx/values.yaml

  
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    wait: true
    hooks:
    # This hook adds the CRDs
      - events: ["presync"]
        showlogs: true
        command: "/bin/sh"
        args: ["-c", "kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml"]
    values:
      - cert-manager/issuer.yaml


  
  - name: mongodb
    namespace: mongo
    createNamespace: true
    chart: bitnami/mongodb
    values:
      - mongo/values.yaml
    wait: true

  - name: mongodb-exporter
    namespace: prometheus
    createNamespace: true
    chart: prometheus-community/prometheus-mongodb-exporter
    values:
      - mongodb-exporter/values.yaml

  
  
  